[FileDialog]
history=file:///home/kevin/media/Emulation/Games, file:///home/kevin/downloads, file:///home/kevin/games/openrct2, file:///home/kevin/documents/ece271, file:///home/kevin/documents/cs506
lastVisited=file:///home/kevin/documents/cs506
qtVersion=5.15.2
shortcuts=file:, file:///home/kevin
sidebarWidth=92
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2;\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0g\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1\x43\0\0\0\x1\0\0\0\0\0\0\0\x43\0\0\0\x1\0\0\0\0\0\0\0\x43\0\0\0\x1\0\0\0\0\0\0\0r\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail
